/*
 * NFT Storage API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package storage.nft.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Deal
 */
public class DealTest {
    private final Deal model = new Deal();

    /**
     * Model tests for Deal
     */
    @Test
    public void testDeal() {
        // TODO: test Deal
    }

    /**
     * Test the property 'batchRootCid'
     */
    @Test
    public void batchRootCidTest() {
        // TODO: test batchRootCid
    }

    /**
     * Test the property 'lastChange'
     */
    @Test
    public void lastChangeTest() {
        // TODO: test lastChange
    }

    /**
     * Test the property 'miner'
     */
    @Test
    public void minerTest() {
        // TODO: test miner
    }

    /**
     * Test the property 'network'
     */
    @Test
    public void networkTest() {
        // TODO: test network
    }

    /**
     * Test the property 'pieceCid'
     */
    @Test
    public void pieceCidTest() {
        // TODO: test pieceCid
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'statusText'
     */
    @Test
    public void statusTextTest() {
        // TODO: test statusText
    }

    /**
     * Test the property 'chainDealID'
     */
    @Test
    public void chainDealIDTest() {
        // TODO: test chainDealID
    }

    /**
     * Test the property 'dealActivation'
     */
    @Test
    public void dealActivationTest() {
        // TODO: test dealActivation
    }

    /**
     * Test the property 'dealExpiration'
     */
    @Test
    public void dealExpirationTest() {
        // TODO: test dealExpiration
    }

}
