/*
 * NFT Storage API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package storage.nft.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import storage.nft.model.ForbiddenErrorResponseError;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ForbiddenErrorResponse
 */
public class ForbiddenErrorResponseTest {
    private final ForbiddenErrorResponse model = new ForbiddenErrorResponse();

    /**
     * Model tests for ForbiddenErrorResponse
     */
    @Test
    public void testForbiddenErrorResponse() {
        // TODO: test ForbiddenErrorResponse
    }

    /**
     * Test the property 'ok'
     */
    @Test
    public void okTest() {
        // TODO: test ok
    }

    /**
     * Test the property 'error'
     */
    @Test
    public void errorTest() {
        // TODO: test error
    }

}
