/*
 * NFT Storage API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package storage.nft.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import storage.nft.model.LinksFile;

/**
 * Links
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-04-29T12:41:03.666Z[GMT]")
public class Links {
  public static final String SERIALIZED_NAME_IPFS = "ipfs";
  @SerializedName(SERIALIZED_NAME_IPFS)
  private String ipfs;

  public static final String SERIALIZED_NAME_HTTP = "http";
  @SerializedName(SERIALIZED_NAME_HTTP)
  private String http;

  public static final String SERIALIZED_NAME_FILE = "file";
  @SerializedName(SERIALIZED_NAME_FILE)
  private List<LinksFile> file = null;


  public Links ipfs(String ipfs) {
    
    this.ipfs = ipfs;
    return this;
  }

   /**
   * Get ipfs
   * @return ipfs
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "ipfs://bafkreidivzimqfqtoqxkrpge6bjyhlvxqs3rhe73owtmdulaxr5do5in7u", value = "")

  public String getIpfs() {
    return ipfs;
  }


  public void setIpfs(String ipfs) {
    this.ipfs = ipfs;
  }


  public Links http(String http) {
    
    this.http = http;
    return this;
  }

   /**
   * Get http
   * @return http
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "http://bafkreidivzimqfqtoqxkrpge6bjyhlvxqs3rhe73owtmdulaxr5do5in7u.ipfs.dweb.link", value = "")

  public String getHttp() {
    return http;
  }


  public void setHttp(String http) {
    this.http = http;
  }


  public Links file(List<LinksFile> file) {
    
    this.file = file;
    return this;
  }

  public Links addFileItem(LinksFile fileItem) {
    if (this.file == null) {
      this.file = new ArrayList<LinksFile>();
    }
    this.file.add(fileItem);
    return this;
  }

   /**
   * Get file
   * @return file
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<LinksFile> getFile() {
    return file;
  }


  public void setFile(List<LinksFile> file) {
    this.file = file;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Links links = (Links) o;
    return Objects.equals(this.ipfs, links.ipfs) &&
        Objects.equals(this.http, links.http) &&
        Objects.equals(this.file, links.file);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ipfs, http, file);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Links {\n");
    sb.append("    ipfs: ").append(toIndentedString(ipfs)).append("\n");
    sb.append("    http: ").append(toIndentedString(http)).append("\n");
    sb.append("    file: ").append(toIndentedString(file)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

